[package]
name = "ringe_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.20.0"
logos = "0.13.0"
regex = "1.8.1"

[build-dependencies]
lalrpop = "0.20.0"
